### ISSUE TITLE
Relationship between bootmetro & Metro-UI-CSS & bootstrap

### ISSUE THREAD

**Issue by victorwoo** [aozora/bootmetro#24]
Hi aozora,

You said bootmetro is based on Metro-UI-CSS, will the changes of the future of Metro-UI-CSS be merged into bootmetro project? What's the goal of bootmetro project (more than Metro-UI-CSS project)?

And another question, what's the significance of using Twitter bootstrap? I think it's a full featured UI framework, if  I desided to use bootmetro + jQuery UI, will them confict or redundant?

Execuse me that I could find your contact information, so I ask question here.
Thank you.

**Comment by EliuX** [comment]
I have seen Metro-UI-CSS looks better, its lighter too (requires several times less javascript than the bootmetro), and has an already integration with datatables which is an strength, and it feels smoother, but bootmetro is based in boostrap which is the most used css framework since the past 3 years, so it offers lots of addons and mods that allows you to code faster. Its not an easy choice.

**Comment by gdefombelle** [comment]
I have been using both Metro-UI-CSS  & bootmetro; i  definetly prefer Metro-UI-CSS because of weight , stability and support. It's beautiful too

**Comment by EliuX** [comment]
Making maths i thing you should use bootmetro if you are a programmer which will design your app and you are not very good in CSS. Metro UI CSS offers more friendly User eXperience, but you have to be open to make your own changes in the future.

**Comment by ejaymejr** [comment]
Metro UI CSS is better because of datatables.  But beyond 10,000 records to display, you will have a problem.  I have done it, but most paginator will have a hard time displaying 10,000 records.
